# Generated by Django 4.2.5 on 2023-09-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CHAR_EXP', 'Character EXP Material'), ('LC_EXP', 'Light Cone EXP Material'), ('RELIC_EXP', 'Relic Exp Material')], default='CHAR_EXP', max_length=9),
        ),
    ]
